### ISSUE TITLE
Склади не видаляє

### ISSUE THREAD

**Issue by Ola535** [dovgyj/helpis.pro#11]
![33](https://user-images.githubusercontent.com/31565508/30080557-ac2c4b1a-928c-11e7-8550-002180a5d377.jpg)
При нажиманні кнопки видалити склад не видаляється!

**Comment by dovgyj** [comment]
Cклад видаляється, просто воно його ще показує з кешу, після того як видаляти склад потрібно ще раз перейти на вкладку "склади"

**Comment by Ola535** [comment]
тепер видаляє
