### ISSUE TITLE
Корзина!

### ISSUE THREAD

**Issue by Ola535** [dovgyj/helpis.pro#3]
При перехооді на корзину чи її очищення пишемо 
В корзине ничего нет.  (темно синім кольором)
(на фон ставимо корзину і висвітляємо )

**Comment by dovgyj** [comment]
Це приблизно так має бути?

**Comment by Ola535** [comment]
Так але шрифт трохи зменшити і на вайбер я скинула фото (там після очищення корзини сама корзина має вміщуватися в білий фон  фото на вайбері)
