### ISSUE TITLE
Замовлення стасус не працює!

### ISSUE THREAD

**Issue by Ola535** [dovgyj/helpis.pro#8]
https://helpis.pro/admin/Zakaz/CreateNote
нічого не працює 
![1](https://user-images.githubusercontent.com/31565508/30074604-cfd81d44-927a-11e7-8c60-a2ae21608bc9.png)

https://www.youtube.com/watch?v=ikqeOxaIKTg&feature=youtu.be

**Comment by dovgyj** [comment]
я подумаю як це виправити, але воно працює після того як перейти на вкладку запрос коли url  такий https://helpis.pro/admin/Zakaz/CreateNote

**Comment by Ola535** [comment]
воно має коректно працювати щоб відповідно до зміни статусу змінювався заданий йому колір

**Comment by dovgyj** [comment]
Колір міняється тільки необхідно обновити кеш(перейти на вкладку замовлення)
