### ISSUE TITLE
Питання!

### ISSUE THREAD

**Issue by Ola535** [dovgyj/helpis.pro#9]
![32](https://user-images.githubusercontent.com/31565508/30074698-208d30d0-927b-11e7-915d-36360e49eeae.jpg)

так  і нічого не відображається хоча біля самого слова питання числиться 3 шт.

**Comment by dovgyj** [comment]
я випралю глюк з  підрахункою питань, а воно попадає в запрос. Проблема закинути його в питання тому що там немає відповідних полів для номера кузова марки
